### ISSUE TITLE
Filter Needed on SearchRequest Object

### ISSUE THREAD

**Issue by olantobi** [Constructor-io/constructorio-java#108]
How do we add filter parameters on a SearchRequest. 

`SearchRequest request = new SearchRequest("peanut butter");`
`request.filter` ?

**Comment by m-abdul** [comment]
Map<String, List<String>> facets = new HashMap<>();
facets.put("color", Arrays.asList("white", "yellow"));
        
SearchRequest request = new SearchRequest("peanut butter");
request.setFacets(facets);
